### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by muskecan** [antichown/0x94TR#2]
Traceback (most recent call last):
  File "/home/lollol/Desktop/pentest/0x94TR/0x94TR.py", line 27, in <module>
    from thirdparty.requests import *
  File "/home/lollol/Desktop/pentest/0x94TR/thirdparty/requests/__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_first(imp.java:879)
	at org.python.core.imp.import_module_level(imp.java:964)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1076)
	at thirdparty.requests$py.f$0(/home/lollol/Desktop/pentest/0x94TR/thirdparty/requests/__init__.py:131)
	at thirdparty.requests$py.call_function(/home/lollol/Desktop/pentest/0x94TR/thirdparty/requests/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:237)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:657)
	at org.python.core.imp.find_module(imp.java:551)
	at org.python.core.PyModule.impAttr(PyModule.java:111)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_logic(imp.java:905)
	at org.python.core.imp.import_module_level(imp.java:970)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importAll(imp.java:1176)
	at org.python.pycode._pyx4.f$0(/home/lollol/Desktop/pentest/0x94TR/0x94TR.py:3154)
	at org.python.pycode._pyx4.call_function(/home/lollol/Desktop/pentest/0x94TR/0x94TR.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.ac1.<init>(Unknown Source)
	at burp.m.a(Unknown Source)
	at burp.ey9.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by antichown** [comment]
yeni sürümü indir urllib3 isteyen kısımı kaldırdım
